apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: mcp-server

images:
  - name: ghcr.io/your-org/mcp-server
    newTag: latest