apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: mcp
  labels:
    app: mcp-server
spec:
  selector:
    app: mcp-server
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP